Repository Esri/calcite-app-components, pull requests merged in 2019-11, with the labels that each got.

#490 Added z-index for disabled and loading panel.
  src/components/calcite-panel/calcite-panel.scss
Labels: 1 - assigned

#489 Spacing updates and calcite-components alignment
  src/assets/styles/_color.scss
  src/components/calcite-action-bar/calcite-action-bar.scss
  src/components/calcite-action-group/calcite-action-group.scss
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/resources.ts
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: 1 - assigned, p - high

#491 fix: calcite-action loading & calcite-flow-item footer in Edge browser
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/resources.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, bug

#484 PickList and ValueList: share more code between lists 461
  .gitignore
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.spec.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: enhancement, refactor

#488 PickList and ValueList: share render methods between lists 461
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: enhancement, refactor

#497 fix: FlowItem - Filter out menu actions defined in the calcite-pick-list and calcite-value-list.
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
Labels: 1 - assigned, bug

#500 fix: flow-item and panel footer buttons
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-panel/calcite-panel.scss
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, bug

#494 Hrobbins/change filter data to fewer props 461
  .gitignore
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.spec.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/tests/commonTests.ts
Labels: enhancement

#499 PickList/ValueList use props not attrs 400
  src/components/calcite-pick-list/shared-list-logic.ts
  src/demos/calcite-pick-list-advanced.html
  src/demos/calcite-pick-list.html
Labels: bug

#505 style(pick-list-group): heading styling
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
Labels: 1 - assigned

#502 fix: Set the property of the component instead of the attribute
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.tsx
Labels: 0 - new, chore

#511 style(action-pad): added missed styles
  src/components/calcite-action-pad/calcite-action-pad.scss
Labels: 1 - assigned

#512 style(block-section): missed style for switch mode
  src/components/calcite-block-section/calcite-block-section.scss
Labels: 1 - assigned

#508 test(block): add tests for loading and disabled properties
  src/components/calcite-block/calcite-block.e2e.ts
Labels: chore

#510 chore: Hump day Bump day
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#515 style(block-section): label spacing in switch mode
  src/components/calcite-block-section/calcite-block-section.scss
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, p - low

#520 refactor: use CSS vars for calculations
  src/assets/styles/_layout.scss
Labels: 1 - assigned, p - low, refactor

#514 fix: Shell styling for TipManager
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/demos/calcite-shell-full-window.html
  src/demos/calcite-shell.html
Labels: 1 - assigned

#525 docs: Add Semantic PR readme/info
  CONTRIBUTING.md
Labels: 1 - assigned, doc

#522 remove Edge's nonStandard broken clear btn
  src/components/calcite-filter/calcite-filter.scss
Labels: bug

#529 style: Updating base spacing to 16px
  src/assets/styles/_animation.scss
  src/assets/styles/_layout.scss
Labels: 1 - assigned

#509 Hrobbins/picklist sticky filter 503
  README.md
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/resources.ts
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-value-list/calcite-value-list.scss
Labels: enhancement

#534 style: explicit values for flex shorthand
  src/assets/styles/_base.scss
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-shell/calcite-shell.scss
Labels: 1 - assigned

#535 style(calcite-value-list-item) Remove box-shadow border from last child.
  src/components/calcite-value-list-item/calcite-value-list-item.scss
Labels: 1 - assigned

#532 Hrobbins/a11y e2e tests 385
  src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-tip-group/calcite-tip-group.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip/calcite-tip.e2e.ts
  src/components/calcite-value-list/calcite-value-list.e2e.ts
Labels: chore

#533 feat: Add property & event for toggling the opening or closing of the TipManager
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip-manager/resources.ts
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, enhancement

#526 chore: Update issue templates
  .github/ISSUE_TEMPLATE/accessibility.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/new-component.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/research.md
  .github/ISSUE_TEMPLATE/tooling.md
Labels: 1 - assigned, chore

#541 feat: CalcitePanel - Add scale property to set dynamic height #513
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, enhancement

#544 fix(value-list-item): last child selection
  src/components/calcite-value-list-item/calcite-value-list-item.scss
Labels: 1 - assigned, p - high

#550 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore, p - low

#556 fix(panel): header-content layout when leading slot is empty
  src/assets/styles/_base.scss
  src/assets/styles/_layout.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
Labels: 1 - assigned, p - medium

#537 fix: Stencil build warnings
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/calcite-pick-list.html
Labels: 1 - assigned, bug, help wanted

#549 docs: add jsdocs for slot's for the list elements
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: doc

#558 feat(action): add ability to set appearance to clear
  src/assets/styles/_color.scss
  src/assets/styles/_mixins.scss
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/demos/calcite-action.html
Labels: 1 - assigned, p - medium

#563 chore: Add doc issue template
  .github/ISSUE_TEMPLATE/accessibility.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/research.md
Labels: 1 - assigned, chore

#567 fix: calcite-block disabled state doesn't 'hide' slider handle #560
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/utils/CalciteScrim.tsx
Labels: 1 - assigned, bug

#570 fix(action): focus outline a11y
  src/assets/styles/_layout.scss
  src/components/calcite-action/calcite-action.scss
Labels: 1 - assigned, p - high

#576 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#578 Lists: added tests to validate event data
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list/shared-list-tests.ts
Labels: enhancement

#584 Travis CI Node Version Update
  .travis.yml
Labels: hotfix

#574 removed text node from fitler label.
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-filter/resources.ts
  src/components/calcite-pick-list/resources.ts
Labels: enhancement

#559 feat: value list drag drop keyboard support 356
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/utils/array.ts
  src/components/utils/dom.ts
  src/demos/calcite-value-list-advanced.html
  src/demos/calcite-value-list.html
Labels: enhancement

#582 fix(block): hide collapse icon when a control is provided in Edge
  src/components/calcite-block/calcite-block.tsx
Labels: bug

#585 prevent deselection for single-select lists
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
Labels: bug

#589 fix: Convert js files from es6 to es5
  src/demos/demoPageReloader.js
  src/demos/head.js
Labels: 1 - assigned
