Repository Esri/calcite-app-components, pull requests merged in 2019-09, with the labels that each got.

#221 Mobile version of demo nav
  src/components/calcite-demo-nav/calcite-demo-nav.scss
  src/components/calcite-demo-nav/calcite-demo-nav.tsx
Labels: enhancement

#224 Enhancement: Add events to notify app when panel size has changed #223
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
Labels: 1 - assigned

#243 Drop unneeded dependency
  package-lock.json
  package.json
Labels: chore

#241 Hrobbins/bug tip manager no tips 214
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
Labels: bug

#247 Change prefer-conditional-expression rule severity to warning.
  tslint.json
Labels: chore

#255 Hrobbins/npm publish preparation
  .gitignore
  .npmrc
  README.md
  package-lock.json
  package.json
  stencil.config.ts
  support/prepublish.js
  support/release.sh
Labels: chore

#256 chore: initial changelog
  CHANGELOG.md
Labels: doc

#141 PickList Component
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/calcite-action-pad/readme.md
  src/components/calcite-block/readme.md
  src/components/calcite-demo-nav/calcite-demo-nav.tsx
  src/components/calcite-demo-nav/readme.md
  src/components/calcite-example/readme.md
  src/components/calcite-flow/readme.md
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-group/calcite-pick-list-row.e2e.ts
  src/components/calcite-pick-list-group/resources.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-row.e2e.ts
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/resources.ts
  src/components/calcite-shell/readme.md
  src/components/calcite-tip-group/readme.md
  src/components/utils/guid.ts
  src/demos/calcite-pick-list.html
Labels: new component

#271 Issue 192: Use JSDoc for slots.
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/readme.md
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/readme.md
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/readme.md
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell-panel/readme.md
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-shell/readme.md
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/readme.md
Labels: chore, doc

#275 fix: pre-populate state with preselected items
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
Labels: bug

#283 PickerList styles
  src/assets/styles/_base.scss
  src/assets/styles/_color.scss
  src/assets/styles/_layout.scss
  src/assets/styles/_mixins.scss
  src/assets/styles/_type.scss
  src/assets/styles/includes.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-group/resources.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-row.e2e.ts
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/resources.ts
  src/components/utils/CalciteIcon.tsx
  src/demos/calcite-pick-list.html
Labels: 1 - assigned, p - high

#232 Asangma/full width demo
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, enhancement

#267 refactor: remove tabindex @Prop
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
Labels: enhancement, refactor

#277 fix: flow demo chang width to max-width
  src/demos/calcite-flow.html
Labels: bug

#293 remove undocumented `dismissed` attribute in favor of hidden. A devel…
  src/components/calcite-tip/calcite-tip.scss
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/resources.ts
Labels: 1 - assigned, p - low

#281 add disabled prop to pick-list-item
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
Labels: enhancement

#295 PickList - keyboard toggles
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
Labels: enhancement

#299 deprecating props on pickList
  src/components/calcite-pick-list/calcite-pick-list.tsx
Labels: hotfix

#296 Component: CalcitePanel
  README.md
  src/components/calcite-demo-nav/calcite-demo-nav.tsx
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/readme.md
  src/components/calcite-panel/resources.ts
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.e2e.ts
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.tsx
  src/components/calcite-shell-floating-panel/readme.md
  src/components/calcite-shell-floating-panel/resources.ts
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell-panel/readme.md
  src/components/calcite-shell/readme.md
  src/demos/calcite-panel.html
  src/demos/calcite-shell-full-window.html
  stencil.config.ts
Labels: 1 - assigned, doc, enhancement, new component, p - medium, refactor

#312 Update stencil to 1.5.3
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip-manager/resources.ts
  src/components/calcite-tip/calcite-tip.e2e.ts
Labels: 1 - assigned, chore

#314 Change @esri/calcite-colors version to NPM package.
  package-lock.json
  package.json
  src/assets/styles/_color.scss
  src/assets/styles/includes.scss
Labels: chore

#305 add pre-select logic on componentDidLoad
  src/components/calcite-pick-list/calcite-pick-list.tsx
Labels: bug

#142 Filter Component
  package-lock.json
  package.json
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/resources.ts
  src/demos/calcite-pick-list.html
Labels: new component, p - high

#316 replace npm install with npm ci in preversion script
  package.json
Labels: enhancement

#319 Enhancement: CalciteAction text modes
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/readme.md
  src/components/calcite-action/resources.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/demos/calcite-action.html
  src/demos/calcite-shell-full-window.html
  src/demos/calcite-shell-rtl.html
  src/demos/calcite-shell.html
Labels: 1 - assigned, enhancement, p - medium
