Repository Esri/calcite-app-components, pull requests merged in 2019-08, with the labels that each got.

#151 Add i18n strings for tip buttons
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip-manager/resources.ts
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/resources.ts
Labels: 1 - assigned, bug

#160 update @stencil/core to v1.2.5
  .npmrc
  package-lock.json
  package.json
Labels: chore

#163 calcite-action disabled property
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/demos/calcite-action.html
Labels: 1 - assigned, enhancement

#165 #164 add collapsed property to hide content
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
Labels: 1 - assigned, enhancement

#169 Slawt Dawk
  src/components/calcite-action-bar/readme.md
  src/components/calcite-block/readme.md
  src/components/calcite-flow-item/readme.md
  src/components/calcite-shell-panel/readme.md
  src/components/calcite-shell/readme.md
  src/components/calcite-tip/readme.md
Labels: 3 - installed, doc

#178 Disabled style for action
  src/assets/styles/_color.scss
  src/components/calcite-action/calcite-action.scss
  src/demos/calcite-shell.html
Labels: 1 - assigned

#180 Add event for when a component is closed
  src/components/calcite-floating-panel/calcite-floating-panel.e2e.ts
  src/components/calcite-floating-panel/calcite-floating-panel.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.e2e.ts
  src/components/calcite-tip/calcite-tip.tsx
Labels: 1 - assigned

#188 contextual panel fix #181
  src/components/calcite-shell/readme.md
Labels: 3 - installed, doc

#191 Issue #177: Reference partials by exact name to ensure rebuild.
  src/assets/styles/includes.scss
Labels: tooling

#194 Issue #190: Inline calcite-component utilities to avoid unnecessary bundling
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/utils/dom.ts
Labels: architecture, bug, p - medium

#166 Picker component: End to End Tests
  src/components/calcite-picker-group/calcite-picker-group.tsx
  src/components/calcite-picker-group/calcite-picker-row.e2e.ts
  src/components/calcite-picker-group/resources.ts
  src/components/calcite-picker-row/calcite-picker-row.e2e.ts
  src/components/calcite-picker-row/calcite-picker-row.tsx
  src/components/calcite-picker-row/resources.ts
  src/components/calcite-picker/calcite-picker.e2e.ts
  src/components/calcite-picker/calcite-picker.tsx
  src/components/calcite-picker/resources.ts
  src/demos/calcite-picker.html
Labels: chore, new component

#167 Remove the editing code from picker
  src/components/calcite-picker-row/calcite-picker-row.tsx
  src/components/calcite-picker/calcite-picker.tsx
  src/demos/calcite-picker.html
Labels: chore

#168 rename picker-row to picker-item
  src/components/calcite-picker-group/calcite-picker-group.tsx
  src/components/calcite-picker-group/calcite-picker-row.e2e.ts
  src/components/calcite-picker-group/resources.ts
  src/components/calcite-picker-item/calcite-picker-item.scss
  src/components/calcite-picker-item/calcite-picker-item.tsx
  src/components/calcite-picker-item/calcite-picker-row.e2e.ts
  src/components/calcite-picker-item/resources.ts
  src/components/calcite-picker/calcite-picker-row/calcite-picker-row.e2e.ts
  src/components/calcite-picker/calcite-picker.e2e.ts
  src/components/calcite-picker/calcite-picker.tsx
  src/demos/calcite-picker.html
Labels: chore

#209 #208 fix placement bug
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
  src/demos/calcite-shell-rtl.html
  src/demos/calcite-shell.html
Labels: 1 - assigned, bug

#203 Bug: every component should be able to be hidden by attribute
  src/assets/styles/_base.scss
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
  src/components/calcite-tip-manager/calcite-tip-manager.scss
Labels: 1 - assigned, bug

#220 fix flow-item test intermittent errors
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
Labels: hotfix

#235 Issue #207: Update other E2E tests to use utility.
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-example/calcite-example.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow/calcite-flow.e2e.ts
  src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell/calcite-shell.e2e.ts
  src/components/calcite-tip-group/calcite-tip-group.e2e.ts
  src/components/calcite-tip/calcite-tip.e2e.ts
Labels: tooling

#236 @stencil/core@1.3.2
  package-lock.json
  package.json
Labels: chore

#222 pagination icons respect dir=rtl
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/demos/calcite-tip-manager.html
Labels: bug
