Repository Esri/calcite-app-components, pull requests merged in 2019-10, with the labels that each got.

#322 Allow action bar to scroll. nix shell min height
  src/components/calcite-action-bar/calcite-action-bar.scss
  src/components/calcite-shell/calcite-shell.scss
Labels: 1 - assigned

#323 Issue #308: Ensure Block header focus outline is visible.
  src/components/calcite-block/calcite-block.scss
Labels: a11y, bug

#304 Hrobbins/nav landscape 213
  src/components/calcite-demo-nav/calcite-demo-nav.scss
  src/components/calcite-demo-nav/calcite-demo-nav.tsx
Labels: enhancement

#321 #307 key navigation only works on specified target
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
Labels: 1 - assigned, bug, p - low

#330 Issue #152: Add master to branch-building safelist.
  .travis.yml
Labels: tooling

#336 Nixed animations to fix flicker.
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.scss
Labels: 1 - assigned

#337 Update to Stencil core to pre-release 1.60-2.
  package-lock.json
  package.json
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
Labels: 1 - assigned

#344 Update to Stencil 1.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 1 - assigned

#324 feat: sorting event emitter
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/calcite-value-list.html
Labels: enhancement

#345 Light refactoring of background and foreground CSS var usage
  src/assets/styles/_base.scss
  src/components/calcite-action-bar/calcite-action-bar.scss
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip/calcite-tip.scss
Labels: 1 - assigned, p - low

#325 feat: picklistitem rename textHeading prop to textLabel
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/demos/calcite-pick-list.html
  src/demos/calcite-value-list.html
Labels: enhancement, refactor

#341 feat: pickListItem events bubble (remove stopPropagation)
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/calcite-value-list.html
Labels: enhancement

#342 feat: Picklist and ValueList add filterEnabled prop
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/calcite-value-list.html
Labels: enhancement

#352 Bug: Flow animation kicks in if the edit button is clicked
  src/components/calcite-flow/calcite-flow.e2e.ts
  src/components/calcite-flow/calcite-flow.tsx
Labels: 1 - assigned

#355 fix: rename action to menu-actions slot in PickList and ValueList
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: bug

#363 simplify slot
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned

#365 fix(lists): added bg-color rules.
  src/assets/styles/_color.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list/calcite-value-list.scss
Labels: 1 - assigned, p - medium

#369 style(flow-item): using filled version of back icons.
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, p - medium

#349 fix(pick-list demo): fixed incorrect ids in the demo.
  src/demos/calcite-pick-list.html
  src/demos/calcite-value-list.html
Labels: 1 - assigned, p - low

#371 style(block-section): use small calcite-switch.
  src/components/calcite-block-section/calcite-block-section.tsx
Labels: 1 - assigned, p - medium

#300 feat: pick-list compact mode
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/demos/calcite-pick-list.html
Labels: 1 - assigned

#375 fix(panel, flow-item): added min-height.
  src/assets/styles/_base.scss
  src/assets/styles/_layout.scss
Labels: 1 - assigned, p - medium

#373 style(block-section): move border to bottom.
  src/components/calcite-block-section/calcite-block-section.scss
  src/demos/calcite-shell-full-window.html
Labels: 1 - assigned, p - medium

#384 Issue #37: Add a11y test helper.
  package-lock.json
  package.json
  src/tests/commonTests.ts
Labels: a11y, tooling

#389 Issue #292: Move block a11y attributes to shadow DOM.
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.tsx
Labels: a11y, chore

#378 Action : Loading & disabled
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/demos/calcite-action.html
Labels: 1 - assigned, p - high

#394 patch event to send item. Needs a followup test for this.
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
Labels: 1 - assigned, bug, p - high

#397 Kat10140/pick and value list doc
  docs/demos/calcite-value-list.html
  src/components/calcite-pick-list-group/readme.md
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/readme.md
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/readme.md
  src/components/calcite-value-list-item/readme.md
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/calcite-value-list/readme.md
  src/demos/calcite-value-list.html
Labels: doc

#381 Loading disabled scrim with pick list
  src/assets/styles/_color.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/utils/CalciteScrim.tsx
  src/demos/calcite-pick-list.html
Labels: 1 - assigned, p - high

#379 Block : Loading & disabled
  src/assets/styles/_color.scss
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/demos/calcite-block.html
Labels: 1 - assigned, p - high

#380 feat(flow-item, panel): added loading and disabled
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.scss
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/utils/CalciteScrim.tsx
  src/demos/calcite-flow.html
Labels: 1 - assigned, p - high

#410 style(action): added animations for interactive
  src/components/calcite-action/calcite-action.scss
Labels: 1 - assigned

#419 #385 accessible testing for panel components
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell/calcite-shell.e2e.ts
Labels: 1 - assigned, chore

#412 Flow item demo and panel styling
  src/components/calcite-panel/calcite-panel.scss
  src/demos/calcite-flow-item.html
Labels: 3 - installed

#416 calcite flow tests #385
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow/calcite-flow.e2e.ts
Labels: 1 - assigned, chore

#415 #385 accessible action components
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action/calcite-action.e2e.ts
Labels: 1 - assigned, chore

#413 Bug: calcite-flow-item shows header-trailing-content without having menu-actions
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, bug

#420 CalcitePanel: always render slot containers. #354
  src/components/calcite-panel/calcite-panel.tsx
Labels: 1 - assigned, enhancement

#405 feat(value-list): loading and disabled states
  src/components/calcite-value-list/calcite-value-list.scss
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/calcite-value-list/resources.ts
  src/demos/calcite-value-list.html
Labels: 1 - assigned, p - high

#422 #398 fix tip background color
  src/components/calcite-tip/calcite-tip.scss
Labels: 1 - assigned, bug

#388 Update README.md
  README.md
Labels: chore

#387 removing rtl utility class from host
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
Labels: chore

#425 Update calcite components to 1.0.0-beta.11
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#382 fixed event name in demo file
  src/demos/calcite-value-list.html
Labels: chore

#428 #393 remove shell min-width
  src/components/calcite-shell/calcite-shell.scss
Labels: 1 - assigned, enhancement, p - low

#429 bug(value-list): nixed disabled prop from destruct
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: 1 - assigned

#432 bug(flow-item, panel): header text-overflow fix.
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-panel/calcite-panel.scss
  src/demos/calcite-flow-item.html
  src/demos/calcite-flow.html
  src/demos/calcite-pick-list.html
Labels: 1 - assigned

#434 style(panel, value-list): spacing tweaks/
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-value-list/calcite-value-list.scss
Labels: 1 - assigned

#326 fix: pickListItem. spacebar on secondaryAction no longer toggles selection
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: bug

#436 Demo links and minor doc update. Fixed toggle alignment issue in pick list and value list.
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/readme.md
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/readme.md
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/readme.md
  src/components/calcite-flow/readme.md
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/readme.md
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/readme.md
  src/components/calcite-shell-panel/readme.md
  src/components/calcite-shell/readme.md
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/calcite-value-list/readme.md
  src/demos/calcite-flow.html
  src/demos/calcite-pick-list.html
  src/demos/calcite-shell.html
  src/demos/calcite-value-list.html
Labels: 3 - installed, doc

#437 CalciteBlock: Set color vars for dark theme.
  src/assets/styles/_base.scss
  src/components/calcite-block/calcite-block.scss
Labels: 1 - assigned, bug

#438 style(pick-list, value-list, panel, demos): menu-actions slot and other style tweaks
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/demos/calcite-pick-list.html
  src/demos/calcite-shell-full-window.html
  src/demos/calcite-value-list.html
Labels: 1 - assigned

#442 Issue #441: Clean up generated d.ts files before running docs.
  package-lock.json
  package.json
Labels: chore

#443 Revert "Issue #441: Clean up generated d.ts files before running docs."
  package-lock.json
  package.json
Labels: chore

#445 Issue #431: Include linting in CI.
  .travis.yml
  package.json
Labels: tooling

#451 Hrobbins/hotfix move filter setup after render 400
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/demos/calcite-pick-list.html
Labels: bug

#459 fix(value-list-item): removed redundant padding
  src/components/calcite-value-list-item/calcite-value-list-item.scss
Labels: 1 - assigned, p - medium

#458 fix(pick-list-item): summary text overflow fix
  src/assets/styles/_mixins.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/resources.ts
  src/demos/calcite-pick-list.html
Labels: 1 - assigned, p - medium

#465 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: chore

#467 Fixed block caret icon size change when title is long.
  src/components/calcite-block/calcite-block.scss
Labels: 3 - installed

#470 feat(pick-list-item): Exclude text-description in compact mode.
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
Labels: 1 - assigned

#480 Issue #244: Automate GitHub release
  package-lock.json
  package.json
  support/githubReleaseFromChangelog.js
Labels: tooling

#481 Added popover/pick list to full width demo
  src/demos/calcite-shell-full-window.html
  src/demos/head.js
Labels: 3 - installed
