Repository Esri/calcite-app-components, pull requests merged in 2019-12, with the labels that each got.

#596 test(a11y): wire up missing accessible tests.
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.e2e.ts
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell/calcite-shell.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
Labels: a11y, chore

#598 chore: Enable more style linting rules.
  .stylelintrc.json
Labels: chore

#600 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned

#604 chore: Move Flow type to interfaces.ts
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-flow/resources.ts
  src/components/interfaces.ts
Labels: 1 - assigned, chore

#581 shift deselect for lists 551
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
Labels: bug

#610 fix: demo pages in IE11
  src/demos/head.js
Labels: 1 - assigned, chore, p - medium

#613 fix: Only render header when a heading exists or the dismiss button. #566
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-tip/calcite-tip.e2e.ts
  src/components/calcite-tip/calcite-tip.scss
  src/components/calcite-tip/calcite-tip.tsx
  src/demos/calcite-tip.html
Labels: 1 - assigned, bug, p - low

#615 feat: add mixin for interim focus style
  src/assets/styles/_layout.scss
  src/assets/styles/_mixins.scss
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
Labels: 1 - assigned, p - high

#617 fix: JS error in flow demo by removing unnecessary script.
  src/demos/calcite-flow.html
Labels: 1 - assigned, bug

#621 fix(value-list-item): focus outline for handle
  src/components/calcite-value-list-item/calcite-value-list-item.scss
Labels: 1 - assigned

#620 docs: calcite-action-usage documentation
  src/components/calcite-action/readme.md
  src/components/calcite-action/usage/basic.md
Labels: 1 - assigned, doc

#623 fix: keep value-list-item selected in sync with pick-list-item
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
Labels: 1 - assigned, bug, p - high

#602 refactor: update typography and size to use rems
  src/assets/styles/_base.scss
  src/assets/styles/_layout.scss
  src/assets/styles/_type.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/demos/calcite-typography.html
  src/demos/demos.css
Labels: 1 - assigned

#632 fix: Flow animation being removed when subtree of flow-item changes
  src/components/calcite-flow/calcite-flow.e2e.ts
  src/components/calcite-flow/calcite-flow.tsx
Labels: 1 - assigned, bug, p - medium

#630 chore: refactor flow frame CSS
  src/components/calcite-flow/calcite-flow.tsx
Labels: 1 - assigned

#625 chore: deprecate "textDisplay" in favor of "textEnabled"
  src/components/calcite-action/calcite-action.tsx
Labels: 1 - assigned, chore

#627 chore: replace "calcite-example" component with doc
  BOILERPLATE_COMPONENT.md
  CONTRIBUTING.md
  README.md
  src/components/calcite-example/calcite-example.e2e.ts
  src/components/calcite-example/calcite-example.scss
  src/components/calcite-example/readme.md
  src/components/calcite-example/resources.ts
  stencil.config.ts
  stencil.docs.config.ts
Labels: 1 - assigned, chore, enhancement, p - low

#624 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#638 chore(deps): fix vulnerable deps
  package-lock.json
Labels: chore

#639 fix(panel): add min-heights for panel header and footer
  src/assets/styles/_base.scss
  src/assets/styles/_layout.scss
  src/components/calcite-panel/calcite-panel.scss
Labels: 1 - assigned, p - high

#643 fix(panel): flex grow, shrink, basis for panel headers and footers
  src/components/calcite-panel/calcite-panel.scss
Labels: 1 - assigned, p - high

#634 feat: filter updates 597 599
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: enhancement

#645 chore(docs): ensure storybook doc build runs fully
  package.json
  support/tempDocDirCleaner.js
Labels: chore, doc

#646 chore(deps): use concurrently instead of npm-run-all
  package-lock.json
  package.json
Labels: chore

#648 chore: clean up ignore file
  .gitignore
Labels: 1 - assigned, chore

#649 chore(tooling): tsify all files
  .gitignore
  .storybook/webpack.config.js
  .storybook/webpack.config.ts
  package-lock.json
  package.json
  src/demos/demoPageReloader.ts
  src/demos/head.ts
  src/demos/toggles.js
  src/demos/toggles.ts
  src/tests/setup.ts
  stencil.config.ts
  support/demoPageSync.js
  support/demoPageSync.ts
  support/githubReleaseFromChangelog.ts
  support/prepublish.ts
  support/tempDocDirCleaner.ts
  support/tslint.json
  tsconfig-demos.json
Labels: chore, tooling

#653 docs: storybook stories for 4 components
  .gitignore
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: doc

#654 docs(demos): fix docs output
  package.json
  stencil.docs.config.ts
  stencil.storybook.config.ts
Labels: chore, doc

#658 docs(calcite-block): update stories to use property name
  src/components/calcite-block/calcite-block.stories.ts
Labels: chore, doc

#659 docs: [Storybook] Action component stories
  .storybook/resources.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/resources.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/resources.ts
  src/components/interfaces.ts
Labels: 1 - assigned, doc

#661 docs(demos): add missing vendor stylesheet
  .storybook/preview-head.html
Labels: doc

#662 docs: [Storybook] Flow & Panel component stories
  .storybook/resources.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/interfaces.ts
Labels: 1 - assigned, doc

#663 docs: [Storybook] Shell component stories
  .storybook/resources.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-shell-panel/resources.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
Labels: 1 - assigned, doc

#664 fix(flow): remove height rule for flow's frame div
  src/components/calcite-flow/calcite-flow.scss
Labels: 1 - assigned, p - high

#666 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#667 docs: Configure storybook to have getting started info
  .storybook/config.ts
  .storybook/presets.ts
  CONTRIBUTING.md
  GETTING_STARTED.md
  LICENSING.md
  README.md
  package-lock.json
  package.json
  src/1-introduction.stories.mdx
  src/2-getting-started.stories.mdx
  src/3-contributing.stories.mdx
  src/4-code-of-conduct.stories.mdx
  src/5-licensing.stories.mdx
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: 1 - assigned, doc

#651 feat: Setting focus to a calcite-action & Flow Menu keyboard navigation
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/utils/array.ts
  src/components/utils/dom.ts
  src/demos/calcite-flow-item.html
Labels: 1 - assigned, bug, enhancement, p - high

#641 chore: Remove `calcite-demo-nav`
  src/components/calcite-demo-nav/calcite-demo-nav.scss
  src/components/calcite-demo-nav/calcite-demo-nav.tsx
  src/components/calcite-demo-nav/readme.md
  src/demos/advanced/block-with-value-list.html
  src/demos/advanced/flow-adding-items.html
  src/demos/advanced/shell-demo-app-rtl.html
  src/demos/advanced/shell-demo-app.html
  src/demos/advanced/shell-panel-with-action-bar.html
  src/demos/calcite-action-bar.html
  src/demos/calcite-action-pad.html
  src/demos/calcite-action.html
  src/demos/calcite-block.html
  src/demos/calcite-flow-item.html
  src/demos/calcite-flow.html
  src/demos/calcite-panel.html
  src/demos/calcite-pick-list-advanced.html
  src/demos/calcite-pick-list-simple.html
  src/demos/calcite-pick-list.html
  src/demos/calcite-shell-panel.html
  src/demos/calcite-shell.html
  src/demos/calcite-tip-manager.html
  src/demos/calcite-tip.html
  src/demos/calcite-typography.html
  src/demos/calcite-value-list-advanced.html
  src/demos/calcite-value-list.html
  src/demos/demos.css
  src/demos/toggles.ts
  src/index.html
  stencil.config.ts
Labels: 1 - assigned, chore, doc, p - low

#668 chore(demos): ensure demo files are kept in sync on initial load
  package.json
Labels: chore

#677 chore: turn on storybook toolbar so docs can be toggled.
  .storybook/config.ts
Labels: 1 - assigned, chore

#608 fix!: Flow - Remove current panel automatically when back is clicked #586
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/resources.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.e2e.ts
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/interfaces.ts
  src/demos/advanced/block-with-value-list.html
  src/demos/advanced/flow-adding-items.html
  src/demos/advanced/shell-demo-app-full-window.html
  src/demos/advanced/shell-demo-app-rtl.html
  src/demos/advanced/shell-demo-app.html
  src/demos/calcite-action.html
Labels: 1 - assigned, chore, doc, enhancement, p - high, refactor

#580 test(block-section): add a11y tests
  package.json
  src/components/calcite-block-section/calcite-block-section.e2e.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/tests/commonTests.ts
  src/tests/utils.ts
Labels: a11y, chore

#652 feat(block): prevent disabled block content from being tabbed into
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/components/utils/CalciteScrim.tsx
Labels: enhancement

#680 chore: Remove CalciteIcon Helpers
  .storybook/resources.ts
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/resources.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-block-section/calcite-block-section.e2e.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block-section/resources.ts
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/resources.ts
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-filter/resources.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip-manager/resources.ts
  src/components/calcite-tip/calcite-tip.e2e.ts
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/resources.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list-item/resources.ts
  src/components/utils/CalciteIcon.spec.ts
  src/components/utils/CalciteIcon.tsx
Labels: 1 - assigned, chore

#679 chore(linting): enable no-descending-specificity rule
  .stylelintrc.json
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-filter/calcite-filter.scss
Labels: chore

#681 docs(demos): update HTML helper to add missing quotes for attribute values
  .storybook/utils.ts
Labels: doc

#591 feat(shell-panel, action): Add content-detached property to ShellPanel
  src/components/calcite-action-bar/calcite-action-bar.scss
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell-panel/resources.ts
  src/demos/shell/demo-app-full-window.html
Labels: 1 - assigned, p - medium

#672 chore: remove .only from test files
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-value-list/calcite-value-list.e2e.ts
Labels: hotfix

#689 chore: Panels knobs and test
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/resources.ts
Labels: 1 - assigned, chore

#692 fix(panel, shell-panel): flex-flow fix
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/demos/shell/demo-app-full-window.html
Labels: 1 - assigned, p - high

#687 docs(demos): hide duplicate title from docs tab
  .storybook/utils.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: chore, doc

#715 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: chore

#712 fix: prevent window scrolling when using arrow keys in flow-item menu
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, a11y, bug, p - medium

#716 chore: Add slots const for panel and flow
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
Labels: 1 - assigned, chore
