Repository Esri/calcite-app-components, pull requests merged in 2020-02, with the labels that each got.

#798 feat: multiple actions appear side-by-side
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/demos/value-list/doubleAction.html
Labels: enhancement

#799 fix: Replace shadowroot querying with textInput reference.
  src/components/calcite-filter/calcite-filter.tsx
Labels: bug

#805 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#808 fix(panel, flow-item): fix hidden summary and enhances header layout
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.scss
  src/demos/flow/basic.html
Labels: 1 - assigned

#809 fix(block-section): toggle section (with toggleDisplay=switch) when Enter or Space key is pressed
  src/components/calcite-block-section/calcite-block-section.e2e.ts
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block-section/calcite-block-section.tsx
  src/demos/block/basic.html
Labels: a11y, bug, p - high

#810 fix: Action - Remove padding when used without an icon
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.tsx
  src/demos/action/basic.html
Labels: 1 - assigned, bug

#813 chore: bump stencil
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#812 feat: deprecate layout in favor of position
  .storybook/resources.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell/calcite-shell.e2e.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-shell/readme.md
  src/components/calcite-shell/usage/advanced.md
  src/components/calcite-shell/usage/basic.md
  src/components/interfaces.ts
  src/components/utils/CalciteExpandToggle.tsx
  src/components/utils/dom.ts
  src/demos/shell-panel/basic.html
  src/demos/shell/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app-rtl.html
  src/demos/shell/demo-app.html
  src/demos/shell/panel-with-action-bar.html
Labels: 1 - assigned, enhancement, p - low, refactor

#816 chore: rename demo file
  src/demos/value-list/double-action.html
Labels: 1 - assigned, chore

#817 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#814 refactor(dom): Add util for finding slotted elements
  src/components/utils/dom.spec.ts
  src/components/utils/dom.ts
Labels: refactor

#819 chore(demos): tidy up test pages
  src/demos/action-bar/add-action-after-init.html
  src/demos/action-bar/basic.html
  src/demos/action-pad/basic.html
  src/demos/action/add-action-icon-after-init.html
  src/demos/action/basic.html
  src/demos/block/basic.html
  src/demos/block/with-value-list.html
  src/demos/flow-item/basic.html
  src/demos/flow/adding-items.html
  src/demos/flow/basic.html
  src/demos/handle/basic.html
  src/demos/panel/basic.html
  src/demos/pick-list/advanced.html
  src/demos/pick-list/basic.html
  src/demos/shell-panel/basic.html
  src/demos/shell/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app-rtl.html
  src/demos/shell/demo-app.html
  src/demos/shell/panel-with-action-bar.html
  src/demos/sortable-list/basic.html
  src/demos/sortable-list/sortable-blocks.html
  src/demos/tip-manager/basic.html
  src/demos/tip/basic.html
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
  src/demos/value-list/double-action.html
  src/demos/value-list/value-update.html
Labels: chore

#821 feat: styles for a tighter calcite-filter and related styles in pick-list and value-list
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/demos/pick-list/basic.html
  src/demos/value-list/basic.html
Labels: 1 - assigned

#832 chore(storybook): fix docs content
  .storybook/config.ts
  .storybook/utils.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: bug, doc

#831 docs(storybook): fix broken links to components from Storybook notes
  .storybook/utils.ts
Labels: bug, doc

#830 chore(docs): migrate Storybook setup to latest
  .storybook/addons.ts
  .storybook/main.ts
  .storybook/presets.ts
  .storybook/preview.ts
Labels: chore, doc

#811 refactor: Add responsive breakpoints
  src/scss/injected.scss
  src/scss/mixins/variables/_breakpoints.scss
Labels: 1 - assigned, architecture, chore, p - low, question

#833 chore: bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#835 docs: fix broken storybook build
  docs/iframe.html
Labels: doc

#836 fix(Action): Allow SVGs to be slotted into the calcite-action.
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.tsx
  src/demos/action/basic.html
Labels: 1 - assigned, bug, p - medium

#838 build(deps): pin storybook to last stable version
  package-lock.json
  package.json
Labels: chore, doc

#840 build: ensure storybook build has proper module script tags
  package-lock.json
  package.json
  support/ensureStorybookBuildHasModuleScripts.ts
Labels: doc

#847 fix(shell-panel): style for deprecated leading and trailing attributes
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/demos/shell/demo-app-full-window.html
Labels: 1 - assigned

#851 feat: props and style for fab
  src/components/calcite-fab/calcite-fab.e2e.ts
  src/components/calcite-fab/calcite-fab.tsx
  src/components/calcite-fab/readme.md
  src/components/calcite-panel/calcite-panel.scss
  src/components/interfaces.ts
  src/demos/fab/basic.html
Labels: 1 - assigned

#852 feat(block, block-section, filter): add intl props
  src/components/calcite-block-section/calcite-block-section.e2e.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-filter/calcite-filter.tsx
Labels: enhancement

#853 refactor(block, block-section, filter): make intl props optional and add fallbacks
  src/components/calcite-block-section/calcite-block-section.e2e.ts
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-filter/calcite-filter.tsx
Labels: refactor

#854 feat(filter): add placeholder property
  src/components/calcite-filter/calcite-filter.e2e.ts
  src/components/calcite-filter/calcite-filter.tsx
Labels: enhancement

#824 feat(fab): Floating Action Button (FAB) aka FABULOUS!!! component.
  .storybook/resources.ts
  package-lock.json
  package.json
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-fab/calcite-fab.e2e.ts
  src/components/calcite-fab/calcite-fab.scss
  src/components/calcite-fab/calcite-fab.stories.ts
  src/components/calcite-fab/calcite-fab.tsx
  src/components/calcite-fab/readme.md
  src/components/calcite-fab/resources.ts
  src/components/calcite-fab/usage/basic.md
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-handle/calcite-handle.e2e.ts
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
  src/components/interfaces.ts
  src/demos/fab/basic.html
  src/demos/flow/basic.html
  src/demos/shell/demo-app-full-window.html
Labels: 1 - assigned, architecture, doc, new component, p - medium

#837 feat(action): Add icon property to display calcite-icon.
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-action/calcite-action.tsx
Labels: 1 - assigned, enhancement, p - medium

#842 feat(flow-item,panel): Add an onscroll event for FlowItem and Panel
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/demos/flow-item/basic.html
  src/demos/panel/basic.html
Labels: 1 - assigned, enhancement, p - low

#856 docs: drop version from @deprecated tags
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/readme.md
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action-pad/readme.md
  src/components/calcite-action/readme.md
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block-section/readme.md
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/readme.md
  src/components/calcite-fab/readme.md
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-filter/readme.md
  src/components/calcite-flow-item/readme.md
  src/components/calcite-panel/readme.md
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell-panel/readme.md
Labels: doc

#858 fix(action-bar): removed default return from getCalcitePosition
  src/components/utils/CalciteExpandToggle.tsx
  src/components/utils/dom.ts
Labels: 1 - assigned

#861 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore
