Repository Esri/calcite-app-components, pull requests merged in 2020-05, with the labels that each got.

#950 feat: new calcite-shell-center-row component and updated slot for calcite-shell
  src/components/calcite-shell-center-row/calcite-shell-center-row.e2e.ts
  src/components/calcite-shell-center-row/calcite-shell-center-row.scss
  src/components/calcite-shell-center-row/calcite-shell-center-row.tsx
  src/components/calcite-shell-center-row/resources.ts
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-shell/readme.md
  src/components/calcite-shell/resources.ts
  src/demos/shell/block-configurations.html
  src/demos/shell/demo-app-advanced-2.html
  src/demos/shell/demo-app-advanced-center-row.html
  src/demos/shell/demo-app-advanced.html
Labels: 1 - assigned

#951 chore: bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#953 feat(panel): tweak for FAB slot when h-scroll
  src/components/calcite-panel/calcite-panel.scss
  src/demos/shell/demo-app-advanced-center-row.html
Labels: 1 - assigned, p - low

#954 docs(shell-center-row): tip-manager usage
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/usage/advanced.md
  src/components/calcite-shell/usage/basic.md
Labels: 1 - assigned, doc

#961 docs: Update storybook home info and link to calcite-components
  src/1-introduction.stories.mdx
Labels: 1 - assigned, doc

#944 chore(changelog): add script to preview changelog since last release
  package.json
Labels: chore, tooling

#962 fix(block-section): added rtl check and css
  src/components/calcite-block-section/calcite-block-section.tsx
  src/demos/block/basic.html
Labels: 1 - assigned

#960 feat(shell-center-row, shell-panel): move and reduce styles
  src/components/calcite-shell-center-row/calcite-shell-center-row.scss
  src/components/calcite-shell-panel/calcite-shell-panel.scss
Labels: 1 - assigned

#966 fix(calcite-filter): added rtl check and updated styles
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/demos/pick-list/advanced.html
Labels: 1 - assigned, bug

#968 fix(tip-manager): changed focus style to avoid hidden ring
  src/components/calcite-tip-manager/calcite-tip-manager.scss
Labels: 1 - assigned

#969 chore(changelog): use touch alternative
  package.json
Labels: chore

#963 docs: Add a11y to storybook
  .storybook/main.ts
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-fab/calcite-fab.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: 1 - assigned, doc

#970 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#971 refactor!: Remove deprecated properties and slots from components
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell/calcite-shell.e2e.ts
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-shell/resources.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/interfaces.ts
  src/components/utils/dom.ts
  src/demos/shell/block-configurations.html
  src/demos/shell/demo-app-advanced-2.html
  src/demos/shell/demo-app-advanced-center-row.html
  src/demos/shell/demo-app-advanced.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app.html
  tsconfig.json
Labels: 1 - assigned, breaking, chore

#974 refactor: fix build errors
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/utils/CalciteExpandToggle.tsx
Labels: 1 - assigned, bug

#972 feat(flow-item): added slot that hydrates header-leading-content of calcite-panel
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/demos/flow/basic.html
Labels: 1 - assigned

#975 docs(action-bar, action-pad): add tooltip-prop stories
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
Labels: doc

#977 chore(changelog): clean up temp files generated when creating the preview
  package.json
Labels: chore, p - low

#976 feat(action-pad, action-group): add horizontal layout
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-group/calcite-action-group.scss
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action-pad/resources.ts
  src/components/interfaces.ts
  src/demos/action-pad/basic.html
Labels: 1 - assigned

#979 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#982 chore(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#983 refactor(dom): enhance getSlotted to process direct children
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/utils/dom.spec.ts
  src/components/utils/dom.ts
Labels: refactor

#984 chore(deps): fix npm audit
  package-lock.json
Labels: chore

#964 chore: Use calcite-scrim component
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-value-list/calcite-value-list.scss
  src/components/utils/CalciteScrim.tsx
Labels: 2 - in development, chore, refactor

#985 chore: use Travis environment vars for notification setup
  .travis.yml
Labels: chore

#987 chore: fix scrim theme
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/utils/dom.ts
Labels: 1 - assigned, chore

#988 chore: encrypted notification settings
  .travis.yml
Labels: chore

#990 chore(standard-version): use changelogHeader replacement
  .versionrc.json
Labels: chore

#992 chore(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#989 build: drop ci-linting
  .travis.yml
Labels: chore

#991 docs(changelog): simplify header
  .versionrc.json
Labels: chore, doc

#994 build(travis): set up calcite-app-components@next publishing
  .travis.yml
  .versionrc.json
  package.json
  support/prepNextDeploymentForTravis.sh
Labels: enhancement, tooling

#995 fix(block-section): rtl class was getting incorrectly applied
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block-section/calcite-block-section.tsx
  src/demos/_assets/demos.css
Labels: 1 - assigned

#999 chore: update travis CI to use Teams instead of Slack
  .travis.yml
Labels: 1 - assigned, chore

#1001 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#1003 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore
