Repository Esri/calcite-app-components, pull requests merged in 2020-03, with the labels that each got.

#864 docs(storybook): fix all relative readme links
  .storybook/utils.ts
Labels: doc

#865 chore: use optional chaining wherever applicable
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/tests/utils.ts
Labels: chore

#820 feat(pick-list): add removable prop
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/demos/pick-list/basic.html
Labels: enhancement

#863 fix(block-section): increased top and bottom margins on block-section label to fix focus ring overlap
  src/components/calcite-block-section/calcite-block-section.scss
  src/demos/shell/demo-app-full-window.html
Labels: 1 - assigned

#867 fix(flow-item): update to only show fab-container when fab slot is used
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned

#869 build: fix shared list logic types.
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: chore

#872 fix(action): When using tooltips with an action, browsers title popup shows up
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.tsx
Labels: 1 - assigned, bug

#876 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#878 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#879 refactor(pick-list,value-list): improve shared logic typings
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: refactor

#843 feat(flow-item,panel): Add intl string properties.
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
Labels: 1 - assigned, enhancement, intl, p - low

#844 feat(tip,tip-manager): Add intl string properties.
  src/components/calcite-tip-group/calcite-tip-group.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip-manager/resources.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/resources.ts
Labels: 1 - assigned, enhancement, intl, p - low

#823 feat(action-pad,action-bar): Add intl string properties.
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/resources.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action-pad/resources.ts
  src/components/utils/CalciteExpandToggle.tsx
Labels: 1 - assigned, enhancement, intl

#880 chore: drop Storybook build fixing script
  package-lock.json
  package.json
  support/ensureStorybookBuildHasModuleScripts.ts
Labels: chore

#870 refactor(dom): revisit getSlotted API and usage
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-tip/calcite-tip.tsx
  src/components/utils/dom.spec.ts
  src/components/utils/dom.ts
Labels: refactor

#881 build(lint): set up ESLint
  .eslintrc.json
  .lintstagedrc.json
  .storybook/utils.ts
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-group/calcite-action-group.tsx
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-fab/calcite-fab.stories.ts
  src/components/calcite-fab/calcite-fab.tsx
  src/components/calcite-filter/calcite-filter.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-handle/calcite-handle.tsx
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-sortable-list/calcite-sortable-list.tsx
  src/components/calcite-tip-group/calcite-tip-group.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.stories.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/components/utils/CalciteExpandToggle.tsx
  src/components/utils/dom.spec.ts
  src/components/utils/dom.ts
  src/demos/_assets/demoPageReloader.ts
  src/demos/_assets/head.ts
  src/demos/_assets/toggles.ts
  support/.eslintrc.json
  tslint.json
Labels: chore

#883 feat(flow-item): Fix count for menu-actions
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/demos/flow-item/basic.html
  src/demos/flow/adding-items.html
  src/demos/flow/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app-rtl.html
  src/demos/shell/demo-app.html
Labels: 1 - assigned, bug, p - medium

#885 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#884 docs(readme): Enhance with more information
  FAQ.md
  README.md
Labels: 1 - assigned, doc, p - low

#890 fix(action): Add slotChildNodesFix to stencil config extras
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  stencil.config.ts
Labels: 1 - assigned, enhancement

#891 chore: Bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#893 chore: update project config
  stencil.config.ts
  tsconfig.json
Labels: chore

#892 build(deps): fix vulnerable deps
  package-lock.json
Labels: chore

#887 feat(value-list, pick-list): support ↑↓ arrow keys for navigation and value selection when multiple mode is disabled
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/value-list/basic.html
Labels: a11y, enhancement

#897 feat(block): drop open/close icon
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/resources.ts
  src/demos/block/basic.html
Labels: enhancement

#895 fix(block): use CSS grid to improve header layout
  src/components/calcite-block/calcite-block.scss
Labels: enhancement

#899 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#898 docs(fab): fix storybook in edge
  src/components/calcite-fab/calcite-fab.stories.ts
Labels: 1 - assigned
