Repository Esri/calcite-app-components, pull requests merged in 2020-07, with the labels that each got.

#1030 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#1036 docs(changelog): ensure changelog includes entries from prereleases
  package.json
  support/ensureNonPrereleaseChangelog.ts
Labels: doc, tooling

#1032 fix(shell-center-row): Error when no action-bar is provided
  src/components/calcite-shell-center-row/calcite-shell-center-row.tsx
  src/tests/utils.ts
Labels: 1 - assigned, bug

#1039 build(deps): bump versions
  package-lock.json
  package.json
  src/components/calcite-block-section/calcite-block-section.tsx
Labels: 1 - assigned

#1041 build(deps): bump versions
  package-lock.json
  package.json
  src/components/calcite-fab/calcite-fab.tsx
Labels: chore

#1043 docs: fix changelog handling script
  package-lock.json
  package.json
  support/ensureNonPrereleaseChangelog.ts
Labels: doc

#1045 fix(panel): slot-container height
  src/components/calcite-panel/calcite-panel.scss
Labels: 1 - assigned

#1046 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#1047 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#1048 fix(panel): remove slot-container and associated styles
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
Labels: 1 - assigned, bug
