Repository Esri/calcite-app-components, pull requests merged in 2020-04, with the labels that each got.

#901 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#903 fix(flow-item): fix back button icon not showing up
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: bug

#905 build: fix release script
  package-lock.json
  package.json
Labels: chore

#907 docs: Fix slot usage for stories and markdown
  src/components/calcite-action-bar/usage/basic.md
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-flow/usage/basic.md
  src/components/calcite-shell/calcite-shell.stories.ts
  src/demos/action-bar/basic.html
  src/demos/flow/adding-items.html
Labels: 1 - assigned, doc

#908 chore: Remove unnecessary usage of calcite-icon
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/usage/basic.md
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action-pad/usage/basic.md
  src/components/calcite-action/usage/basic.md
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/usage/basic.md
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-pick-list/usage/basic.md
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-shell-panel/usage/basic.md
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/usage/advanced.md
  src/components/calcite-shell/usage/basic.md
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-value-list/calcite-value-list.stories.ts
  src/components/calcite-value-list/usage/basic.md
  src/components/utils/CalciteExpandToggle.tsx
Labels: 1 - assigned, chore

#904 feat(action-bar,action-pad): Add tooltipExpand property
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/usage/tooltip.md
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action-pad/usage/tooltip.md
  src/components/utils/CalciteExpandToggle.tsx
  src/demos/action-bar/basic.html
  src/demos/action-pad/basic.html
Labels: 1 - assigned, enhancement

#911 fix(pick-list, value-list): Fix icon for selected circle
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
Labels: 1 - assigned, bug

#912 chore: remove use of calcite-icon if possible
  src/demos/action-bar/add-action-after-init.html
  src/demos/action-bar/basic.html
  src/demos/action-pad/basic.html
  src/demos/action/basic.html
  src/demos/block/with-value-list.html
  src/demos/flow/adding-items.html
  src/demos/pick-list/advanced.html
  src/demos/pick-list/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app-rtl.html
  src/demos/shell/demo-app.html
  src/demos/shell/panel-with-action-bar.html
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
  src/demos/value-list/double-action.html
  src/demos/value-list/value-update.html
Labels: 1 - assigned, chore

#914 chore: fix test app
  src/demos/value-list/advanced.html
Labels: 1 - assigned

#913 fix(action): Support slotting icon after initialization
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.tsx
  src/demos/action/add-action-icon-after-init.html
Labels: 1 - assigned, bug

#915 chore: use the force
  src/components/calcite-action/calcite-action.tsx
Labels: 1 - assigned

#917 build(deps): bump versions
  .lintstagedrc
  package-lock.json
  package.json
Labels: chore

#920 fix(action, flow, pick-list, sortable-list, tip-manager, value-list): react to DOM mutations earlier to avoid stagnant renders
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-sortable-list/calcite-sortable-list.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: bug, p - high

#921 fix(value-list): restore DND setup
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: bug, p - high

#922 fix(pick-list-item): update filled circle icon setup
  package-lock.json
  package.json
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
Labels: bug

#926 docs(action,fab): fix edge legacy stories.
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-fab/calcite-fab.stories.ts
Labels: 1 - assigned, doc

#925 docs: document supported browsers #924
  README.md
Labels: 1 - assigned, doc, enhancement

#933 chore(storybook): fix createComponentHTML storybook util
  .storybook/main.js
  .storybook/preview.js
  .storybook/resources.js
  .storybook/theme.js
  .storybook/utils.js
  .storybook/utils.ts
  .storybook/webpack.config.js
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-fab/calcite-fab.stories.ts
Labels: chore, tooling

#934 refactor: drop classnames
  package.json
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow/calcite-flow.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-tip-manager/calcite-tip-manager.tsx
Labels: chore, refactor

#918 refactor(pick-list-item): avoid setting icon when unselected
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
Labels: chore, refactor

#928 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#939 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#932 chore(linting): set up @stencil-eslint rules
  .eslintrc.json
  package-lock.json
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-block-section/calcite-block-section.tsx
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/resources.ts
  src/components/calcite-handle/calcite-handle.tsx
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-sortable-list/calcite-sortable-list.tsx
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
  tsconfig-eslint.json
Labels: chore

#906 feat: typographic reduction and spacing updates
  LICENSING.md
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-block-section/resources.ts
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-block/resources.ts
  src/components/calcite-fab/calcite-fab.scss
  src/components/calcite-fab/calcite-fab.tsx
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-handle/calcite-handle.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/components/interfaces.ts
  src/demos/shell/block-configurations.html
  src/demos/shell/demo-app-advanced-2.html
  src/demos/shell/demo-app-advanced.html
  src/demos/shell/demo-app-full-window.html
  src/scss/includes/_header.scss
  src/scss/mixins/variables/_typography.scss
  src/scss/mixins/variables/theme/_light.scss
Labels: 1 - assigned, enhancement

#942 chore: revisit prepublish error messaging
  support/prepublish.ts
Labels: chore

#943 feat: use less confusing icons in pick-list and value-list
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
  src/demos/pick-list/advanced.html
Labels: 1 - assigned

#946 feat: replace focus ring mixin and added new mixin where needed
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-handle/calcite-handle.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip/calcite-tip.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/demos/tip/basic.html
  src/scss/mixins/_utilities.scss
Labels: 1 - assigned

#948 fix(block): loader UI bug
  src/components/calcite-block/calcite-block.scss
Labels: 1 - assigned
