Repository Esri/calcite-app-components, pull requests merged in 2020-08, with the labels that each got.

#1051 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#1050 feat(panel): Add tooling to test onscroll event for FlowItem and Panel #842 #859
  src/components/calcite-panel/calcite-panel.e2e.ts
Labels: 1 - assigned, enhancement

#1053 docs: fix boolean attribute generation in story util
  .storybook/utils.ts
Labels: doc

#1054 chore(deps): tidy up
  package-lock.json
  package.json
Labels: chore

#1058 build(deps): bump versions
  package-lock.json
  package.json
Labels: chore

#1059 feat(value-list): allow dragging items between lists
  src/components/calcite-sortable-list/calcite-sortable-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
  src/tests/utils.ts
Labels: enhancement
