Repository Esri/calcite-app-components, pull requests merged in 2020-06, with the labels that each got.

#1002 docs(pick-list): add story for nested items
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
Labels: doc

#1004 fix(action): Prevent disabled buttons from being clicked or tabbed into
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.scss
Labels: 1 - assigned

#1005 chore(types): inline type for panel focus ID
  src/components/calcite-panel/calcite-panel.tsx
Labels: chore

#1010 fix(panel, flow-item): Make sure the FAB is always stacked higher than slot content.
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-panel/resources.ts
  src/demos/panel/basic.html
Labels: 1 - assigned, bug

#1011 feat(flow-item): Use calcite-popover for menu actions
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, enhancement

#1012 fix(value-list): ensure keyboard-enabled DND stays active when moving items around
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.e2e.ts
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: a11y, bug

#1019 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#1021 fix(action): fix icon scale
  src/components/calcite-action/calcite-action.tsx
  src/demos/shell/demo-app-advanced.html
Labels: 1 - assigned

#1022 build(deps): bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#1025 fix(action-bar): Sync expanded state with new children
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/demos/action-bar/add-action-after-init.html
Labels: 0 - new, bug

#1028 fix(pick-list): hide non-nested groups that do not match filter
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/shared-list-logic.ts
Labels: bug
