Repository Esri/calcite-app-components, pull requests merged in 2020-01, with the labels that each got.

#723 docs: Storybook - Add knob for RTL/LTR toggle for each component
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: 1 - assigned, bug

#713 fix: focus button styles
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
Labels: 1 - assigned, a11y, bug, p - high

#724 fix: FlowItem RTL trailing icon isn't on the far side #721
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-panel/calcite-panel.scss
Labels: 1 - assigned, bug

#725 fix: action display on edge.
  src/components/calcite-action/calcite-action.scss
Labels: 1 - assigned, bug, p - high

#727 fix: addresses safari bugs with pick-list and value-list
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-value-list/calcite-value-list.scss
Labels: 1 - assigned, p - high

#655 style: added role="menu" to value and pick list
  src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
Labels: a11y

#583 feat(flow-item, panel): add summary and related styles
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
  src/components/calcite-flow/calcite-flow.scss
  src/components/calcite-panel/calcite-panel.scss
  src/demos/flow-item/basic.html
  src/demos/flow/adding-items.html
Labels: 1 - assigned, p - medium

#670 refactor: action - make text prop required
  src/components/calcite-action/calcite-action.e2e.ts
  src/components/calcite-action/calcite-action.tsx
  src/demos/action/basic.html
  src/demos/block/with-value-list.html
  src/demos/pick-list/basic.html
  src/demos/pick-list/simple.html
  src/demos/shell/demo-app-full-window.html
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
Labels: a11y, refactor

#731 chore: bump stencil to 1.9.0 pre-release
  package-lock.json
  package.json
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-panel/calcite-panel.tsx
  src/components/calcite-pick-list/shared-list-render.tsx
  src/components/calcite-tip/calcite-tip.tsx
  src/demos/action-bar/add-action-after-init.html
  src/demos/action/add-action-icon-after-init.html
  stencil.config.ts
Labels: 1 - assigned, chore

#730 feat: BREAKING CHANGE rename secondary-action slot
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-value-list-item/calcite-value-list-item.tsx
  src/components/calcite-value-list/calcite-value-list.stories.ts
Labels: enhancement, refactor

#709 fix: A shell with only a contextual panel displays on the incorrect side
  src/components/calcite-shell-panel/calcite-shell-panel.tsx
  src/components/calcite-shell-panel/resources.ts
  src/components/calcite-shell/calcite-shell.e2e.ts
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-shell/calcite-shell.tsx
  src/components/calcite-shell/resources.ts
  src/demos/shell/demo-app-full-window-reversed.html
Labels: 1 - assigned, bug, p - medium

#732 docs: replace secondaryAction with secondary-action
  src/components/calcite-pick-list/usage/basic.md
  src/components/calcite-shell/usage/advanced.md
  src/components/calcite-value-list/usage/basic.md
  src/demos/block/with-value-list.html
  src/demos/pick-list/advanced.html
  src/demos/pick-list/basic.html
  src/demos/pick-list/simple.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/demos/shell/demo-app-full-window.html
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
Labels: 1 - assigned, doc

#737 chore(demos): replace inlined SVGs with calcite-icon
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-group/calcite-action-group.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-flow-item/calcite-flow-item.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
  src/demos/action-bar/basic.html
  src/demos/action-pad/basic.html
  src/demos/action/basic.html
  src/demos/block/with-value-list.html
  src/demos/flow/adding-items.html
  src/demos/pick-list/advanced.html
  src/demos/pick-list/basic.html
  src/demos/pick-list/simple.html
  src/demos/shell/demo-app-full-window.html
  src/demos/shell/demo-app-rtl.html
  src/demos/shell/demo-app.html
  src/demos/shell/panel-with-action-bar.html
  src/demos/value-list/advanced.html
  src/demos/value-list/basic.html
Labels: chore

#735 chore: Remove unused utility methods
  src/components/utils/array.ts
  src/components/utils/dom.ts
Labels: 1 - assigned, chore

#690 feat: ActionPad. Add same expand/collapse behavior as ActionBar
  .storybook/resources.ts
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-bar/resources.ts
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.tsx
  src/components/calcite-action-pad/resources.ts
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/resources.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-panel/resources.ts
  src/components/calcite-shell-panel/resources.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-shell/resources.ts
  src/components/interfaces.ts
  src/components/utils/CalciteExpandToggle.tsx
Labels: 1 - assigned, enhancement, p - medium

#720 refactor!: Modify Tip API & remove unused utilities
  src/components/calcite-tip/calcite-tip.e2e.ts
  src/components/calcite-tip/calcite-tip.scss
  src/components/calcite-tip/calcite-tip.stories.ts
  src/components/calcite-tip/calcite-tip.tsx
  src/components/calcite-tip/resources.ts
  src/components/calcite-tip/usage/basic.md
  src/components/utils/localStorage.ts
  src/demos/tip-manager/basic.html
  src/demos/tip/basic.html
Labels: 1 - assigned, enhancement, p - low, refactor

#739 chore(docs): include note sections in docs tab
  .storybook/utils.ts
Labels: chore, doc

#745 chore: bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#741 refactor: styles.
  src/assets/styles/_animation.scss
  src/assets/styles/_color.scss
  src/assets/styles/_type.scss
  src/assets/styles/includes.scss
  src/components/calcite-action-bar/calcite-action-bar.scss
  src/components/calcite-action-group/calcite-action-group.scss
  src/components/calcite-action-pad/calcite-action-pad.scss
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-block-section/calcite-block-section.scss
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-filter/calcite-filter.scss
  src/components/calcite-flow-item/calcite-flow-item.scss
  src/components/calcite-flow/calcite-flow.scss
  src/components/calcite-panel/calcite-panel.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-shell-panel/calcite-shell-panel.scss
  src/components/calcite-shell/calcite-shell.scss
  src/components/calcite-tip-group/calcite-tip-group.scss
  src/components/calcite-tip-manager/calcite-tip-manager.scss
  src/components/calcite-tip/calcite-tip.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/components/calcite-value-list/calcite-value-list.scss
  src/scss/README.md
  src/scss/global.scss
  src/scss/includes/_animation.scss
  src/scss/includes/_component.scss
  src/scss/includes/_header.scss
  src/scss/injected.scss
  src/scss/mixins/_utilities.scss
  src/scss/mixins/variables/_animation.scss
  src/scss/mixins/variables/_layout.scss
  src/scss/mixins/variables/_shadow.scss
  src/scss/mixins/variables/_typography.scss
  src/scss/mixins/variables/theme/_dark.scss
  src/scss/mixins/variables/theme/_light.scss
  src/scss/placeholders/_host.scss
  stencil.config.ts
Labels: 1 - assigned, chore

#749 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#754 chore(demos): replace missed inline SVG icons with calcite-icon
  src/demos/action-bar/add-action-after-init.html
  src/demos/action/add-action-icon-after-init.html
Labels: chore

#756 chore: change config so readme only built on prod build
  package.json
  stencil.config.ts
Labels: chore

#742 feat: setFocus on dismiss button method #740
  src/components/calcite-panel/calcite-panel.e2e.ts
  src/components/calcite-panel/calcite-panel.tsx
  src/demos/panel/basic.html
Labels: 1 - assigned, enhancement

#762 fix(block): prevent unintentional toggling when interacting with a slotted control
  src/components/calcite-block/calcite-block.e2e.ts
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
Labels: bug, refactor

#761 chore(deps): Bump versions.
  package-lock.json
  package.json
Labels: chore

#765 docs: Add summary prop to flow story
  src/components/calcite-flow/calcite-flow.stories.ts
Labels: 1 - assigned, doc

#766 fix: only modify textEnabled when expand functionality is enabled
  src/components/calcite-action-bar/calcite-action-bar.e2e.ts
  src/components/calcite-action-bar/calcite-action-bar.tsx
  src/components/calcite-action-pad/calcite-action-pad.e2e.ts
  src/components/calcite-action-pad/calcite-action-pad.tsx
Labels: 2 - in development, bug

#755 style: dedent HTML template strings
  package-lock.json
  package.json
  src/components/calcite-action-bar/calcite-action-bar.stories.ts
  src/components/calcite-action-pad/calcite-action-pad.stories.ts
  src/components/calcite-block/calcite-block.stories.ts
  src/components/calcite-flow/calcite-flow.stories.ts
  src/components/calcite-panel/calcite-panel.stories.ts
  src/components/calcite-pick-list/calcite-pick-list.stories.ts
  src/components/calcite-shell/calcite-shell.stories.ts
  src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
  src/components/calcite-value-list/calcite-value-list.stories.ts
  src/demos/_assets/head.ts
  src/demos/flow/adding-items.html
  stencil.config.ts
Labels: tooling

#768 chore: cleanup rendering of the header in flow item
  src/components/calcite-flow-item/calcite-flow-item.tsx
Labels: 1 - assigned, chore

#769 chore: cleanup flow slots
  src/components/calcite-flow-item/calcite-flow-item.tsx
  src/components/calcite-flow-item/resources.ts
Labels: 1 - assigned

#750 feat: lists react to value prop changes in items
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-pick-list/shared-list-tests.ts
  src/components/calcite-value-list/calcite-value-list.tsx
  src/demos/value-list/valueUpdate.html
Labels: bug

#776 fix(value-list-item): focus state fix
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/scss/mixins/_utilities.scss
  src/scss/mixins/variables/_layout.scss
  src/scss/mixins/variables/theme/_light.scss
Labels: 1 - assigned

#775 chore(tooling): add script to preview changelog
  package.json
Labels: chore

#785 fix(block): fix block toggling in Edge
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/demos/block/basic.html
Labels: bug

#786 chore(deps): Bump versions.
  .lintstagedrc.json
  package-lock.json
  package.json
Labels: 1 - assigned, chore

#787 chore(tests): update reflects test helper to handle camelCased props
  src/tests/commonTests.ts
Labels: chore

#789 Bump versions
  package-lock.json
  package.json
Labels: 1 - assigned

#788 fix: Calcite-shell-panel remove position relative #782
  src/components/calcite-shell-panel/calcite-shell-panel.scss
Labels: 1 - assigned, bug

#792 feat(action): add scales to Action
  src/components/calcite-action/calcite-action.scss
  src/components/calcite-action/calcite-action.stories.ts
  src/components/calcite-action/calcite-action.tsx
  src/components/calcite-action/readme.md
  src/demos/_assets/demos.css
  src/demos/action/basic.html
Labels: 1 - assigned

#796 fix(action): style updates for compact mode
  src/components/calcite-action/calcite-action.scss
Labels: 1 - assigned

#783 feat: add styling and some updates for pick-list nesting
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-group/resources.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/demos/action-bar/add-action-after-init.html
  src/demos/pick-list/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/scss/mixins/_utilities.scss
Labels: enhancement

#770 feat: Add nesting support to picklist groups
  src/components/calcite-pick-list-group/calcite-pick-list-group.e2e.ts
  src/components/calcite-pick-list-group/calcite-pick-list-group.scss
  src/components/calcite-pick-list-group/calcite-pick-list-group.tsx
  src/components/calcite-pick-list-group/resources.ts
  src/components/calcite-pick-list-item/calcite-pick-list-item.scss
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list-item/resources.ts
  src/components/calcite-pick-list/calcite-pick-list.e2e.ts
  src/components/calcite-pick-list/calcite-pick-list.scss
  src/components/calcite-pick-list/shared-list-logic.ts
  src/components/calcite-value-list-item/calcite-value-list-item.scss
  src/demos/action-bar/add-action-after-init.html
  src/demos/pick-list/basic.html
  src/demos/shell/demo-app-full-window-reversed.html
  src/scss/mixins/_utilities.scss
Labels: enhancement

#797 refactor: Hrobbins/list rename event 773
  src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
  src/components/calcite-pick-list/calcite-pick-list.tsx
  src/components/calcite-value-list/calcite-value-list.tsx
Labels: refactor

#747 feat: drag n drop component 483
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.tsx
  src/components/calcite-handle/calcite-handle.e2e.ts
  src/components/calcite-handle/calcite-handle.scss
  src/components/calcite-handle/calcite-handle.tsx
  src/components/calcite-handle/resources.ts
  src/components/calcite-sortable-list/calcite-sortable-list.e2e.ts
  src/components/calcite-sortable-list/calcite-sortable-list.scss
  src/components/calcite-sortable-list/calcite-sortable-list.tsx
  src/components/calcite-sortable-list/resources.ts
  src/demos/block/basic.html
  src/demos/handle/basic.html
  src/demos/sortable-list/basic.html
  src/demos/sortable-list/sortable-blocks.html
Labels: new component

#793 fix(block): Avoid extra padding applied to slotted icon content
  .storybook/utils.ts
  src/components/calcite-block/calcite-block.scss
  src/components/calcite-block/calcite-block.stories.ts
Labels: bug
